export const ADD_MESSAGES = 'ADD_MESSAGES';
export type ADD_MESSAGES = typeof ADD_MESSAGES;

export const CREATE_USERNAME = 'CREATE_USERNAME'
export type CREATE_USERNAME = typeof CREATE_USERNAME;

export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'
export type CHANGE_SETTINGS = typeof CHANGE_SETTINGS;

